# Generated by Django 4.0.4 on 2022-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
