# Generated by Django 4.0.4 on 2022-04-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_graph_author_alter_graph_folder_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='title',
            field=models.CharField(default='user1', max_length=255),
            preserve_default=False,
        ),
    ]
