version: "3.9"

services:
  flask_notes_prod:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: production
      FLASK_AMQP_URL: amqp://put_prod_user:put_prod_password@rabbitmq:5672/%2F
    command: python notes_on_flask_run_prod.py
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  flask_notes:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
      FLASK_AMQP_URL: amqp://put_dev_user:put_dev_password@rabbitmq:5672/%2F
    command: python notes_on_flask.py
    ports:
      - "8002:5000"
    depends_on:
      - rabbitmq

  rabbitmq:
    build:
      context: .
      dockerfile: ./rabbit/Dockerfile
    ports:
      - "8003:5672"
      - "8004:15672"
