version: "3.9"

services:
  flask_notes:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: notes_on_flask
      FLASK_ENV: development
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
