version: "3.9"

services:
  flask_notes_prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: python notes_on_flask_run_prod.py
    volumes:
      - .:/app
    ports:
      - "8001:8001"

  flask_notes:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
    command: python notes_on_flask.py
    volumes:
      - .:/app
    ports:
      - "8002:5000"

  rabbitmq:
    build:
      context: .
      dockerfile: ./rabbit/Dockerfile
    ports:
      - "8003:5672"
      - "8004:15672"
