"""empty message

Revision ID: 87af04e611c0
Revises: 
Create Date: 2022-04-18 10:07:11.952734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87af04e611c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('tag_connect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.Column('next_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_connect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_connect')
    op.drop_table('tag_connect')
    op.drop_table('tag')
    # ### end Alembic commands ###
